services:
  # Combined Frontend + Backend Service
  - type: web
    name: mutual-fund-tracker-combined
    env: python
    plan: free
    buildCommand: |
      # Install backend dependencies
      echo "Installing backend dependencies..."
      pip install -r backend/requirements.txt
      
      # Install frontend dependencies
      echo "Installing frontend dependencies..."
      cd frontend
      npm install
      
      # Check Node.js and npm versions
      echo "Node.js version: $(node --version)"
      echo "npm version: $(npm --version)"
      
      # Build frontend
      echo "Building frontend..."
      npm run build
      
      # Check if build was successful
      echo "Checking build output..."
      ls -la
      if [ -d "dist" ]; then
        echo "dist directory found, contents:"
        ls -la dist/
      else
        echo "dist directory not found!"
        exit 1
      fi
      
      # Create backend static directory
      echo "Creating backend static directory..."
      mkdir -p ../backend/static
      
      # Copy built frontend files
      echo "Copying built files..."
      cp -r dist/* ../backend/static/
      
      # Verify copy was successful
      echo "Verifying copy..."
      ls -la ../backend/static/
      
      echo "Build completed successfully!"
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false  # You'll set this manually in Render dashboard
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: NODE_VERSION
        value: 18.17.0
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /
    autoDeploy: true
