services:
  # Combined Frontend + Backend Service
  - type: web
    name: mutual-fund-tracker-combined
    env: python
    plan: free
    buildCommand: |
      # Set Python version explicitly
      python3.12 --version
      # Upgrade pip to latest version
      python3.12 -m pip install --upgrade pip
      # Install backend dependencies with pre-compiled wheels
      python3.12 -m pip install --only-binary=all -r backend/requirements.txt
      # Install frontend dependencies
      cd frontend && npm install
      # Build frontend
      npm run build
      # Create backend static directory
      mkdir -p ../backend/static
      # Copy built files
      cp -r dist/* ../backend/static/
      echo "Build completed successfully!"
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false  # You'll set this manually in Render dashboard
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: NODE_VERSION
        value: 22.19.0
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /
    autoDeploy: true
