services:
  # Combined Frontend + Backend Service
  - type: web
    name: mutual-fund-tracker-combined
    env: python
    plan: free
    buildCommand: chmod +x build-production.sh && ./build-production.sh
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false  # You'll set this manually in Render dashboard
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: NODE_VERSION
        value: 22.19.0
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /
    autoDeploy: true
